# Generated by Django 5.0 on 2026-09-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_id", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=100)),
                ("subcategory", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("services", models.TextField(blank=True)),
                ("address", models.TextField(blank=True)),
                ("area", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(default="Coimbatore", max_length=100)),
                ("state", models.CharField(default="Tamil Nadu", max_length=100)),
                ("pincode", models.CharField(blank=True, max_length=10)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("rating", models.FloatField(default=0.0)),
                ("review_count", models.IntegerField(default=0)),
                ("price_range", models.CharField(blank=True, max_length=20)),
                ("open_hours", models.CharField(blank=True, max_length=100)),
                ("search_keywords", models.TextField(blank=True)),
                ("status", models.CharField(default="active", max_length=20)),
            ],
            options={
                "verbose_name_plural": "Businesses",
                "ordering": ["-rating"],
            },
        ),
    ]
